name: CI/CD Pipeline
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
        run: "echo \"😈8😈8😈8 Hahaha this is from Yusuf 😈8😈8😈8\"\n"
