name: CI/CD Pipeline
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: list files
        run: |
          tree

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Check
        run: |
          pip install flake8
          flake8 .

      # - name: Test
      #   run: |
      #     pytest
