name: CI/CD Pipeline
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: list files
        run: |
          tree

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Check
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Unit Test
        run: |
          pytest -v

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/first-web-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/first-web-app:${{ github.sha }}

      - name: Deploy Container to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: devops-web-app
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.DOCKER_USERNAME }}/first-web-app:${{ github.sha }}


